version: "3.8"

services:
  kafka-broker-1:
    build: 
      context: ./kafka
      dockerfile: Dockerfile
    image: nghiadh/kafka-k1b:1.0.0
    # restart: always
    ports:
      - "${KRAFT_1_BROKER_PORT}:${KRAFT_1_BROKER_PORT}"
      - "${KRAFT_1_CONTROLLER_PORT}:${KRAFT_1_CONTROLLER_PORT}"
    environment:
      - KRAFT_ID=${KRAFT_1_ID}
      - KRAFT_HOST_NAME=${KRAFT_1_HOST_NAME}
      - KRAFT_CONTAINER_NAME=${KRAFT_1_CONTAINER_NAME}
      - KRAFT_BROKER_PORT=${KRAFT_1_BROKER_PORT}
      - KRAFT_CONTROLLER_PORT=${KRAFT_1_CONTROLLER_PORT}
      - KRAFT_QUORUM_VOTERS=${KRAFT_QUORUM_VOTERS}
      - KRAFT_CREATE_TOPICS=${KRAFT_DEFAULT_TOPICS}
      - KRAFT_PARTITIONS_PER_TOPIC=${KRAFT_PARTITIONS_PER_TOPIC}

  kafka-broker-2:
    build: 
      context: ./kafka
      dockerfile: Dockerfile
    image: nghiadh/kafka-k1b:1.0.0
    # restart: always
    ports:
      - "${KRAFT_2_BROKER_PORT}:${KRAFT_2_BROKER_PORT}"
      - "${KRAFT_2_CONTROLLER_PORT}:${KRAFT_2_CONTROLLER_PORT}"
    environment:
      - KRAFT_ID=${KRAFT_2_ID}
      - KRAFT_HOST_NAME=${KRAFT_2_HOST_NAME}
      - KRAFT_CONTAINER_NAME=${KRAFT_2_CONTAINER_NAME}
      - KRAFT_BROKER_PORT=${KRAFT_2_BROKER_PORT}
      - KRAFT_CONTROLLER_PORT=${KRAFT_2_CONTROLLER_PORT}
      - KRAFT_QUORUM_VOTERS=${KRAFT_QUORUM_VOTERS}
      - KRAFT_CREATE_TOPICS=${KRAFT_DEFAULT_TOPICS}
      - KRAFT_PARTITIONS_PER_TOPIC=${KRAFT_PARTITIONS_PER_TOPIC}
