version: "3.8"

services:
  kafka:
    build: 
      context: ./kafka
      dockerfile: Dockerfile
    image: nghiadh/kafka-k1b:1.0.0
    # hostname: kafka
    # container_name: kafka
    # restart: always
    ports:
      - "${K1B_PORT}:${K1B_PORT}"
    environment:
      - KRAFT_CONTAINER_HOST_NAME=kafka
      - KRAFT_CREATE_TOPICS=test-topic-1,test-topic-2
      - KRAFT_PARTITIONS_PER_TOPIC=2
      - KRAFT_ID=${K1}
      - KRAFT_BPORT=${K1B_PORT}
      - KRAFT_CPORT=${K1C_PORT}
      - KRAFT_HOST=${K1_HOST}