version: "3.8"

services:
  kafka-1:
    build: 
      context: ./kafka
      dockerfile: Dockerfile
    image: nghiadh/kafka-kraft:1.0.0
    hostname: ${KRAFT_1_HOST_NAME}
    container_name: ${KRAFT_1_CONTAINER_NAME}
    # restart: always
    ports:
      - "${KRAFT_1_BROKER_PORT}:${KRAFT_1_BROKER_PORT}"
      - "${KRAFT_1_CONTROLLER_PORT}:${KRAFT_1_CONTROLLER_PORT}"
    networks:
      - backend
    environment:
      - KAFKA_STORAGE_UUID=${KAFKA_STORAGE_UUID}
      - KRAFT_ID=${KRAFT_1_ID}
      - KRAFT_HOST_NAME=${KRAFT_1_HOST_NAME}
      - KRAFT_CONTAINER_NAME=${KRAFT_1_CONTAINER_NAME}
      - KRAFT_BROKER_PORT=${KRAFT_1_BROKER_PORT}
      - KRAFT_CONTROLLER_PORT=${KRAFT_1_CONTROLLER_PORT}
      - KRAFT_QUORUM_VOTERS=${KRAFT_QUORUM_VOTERS}
      - KRAFT_CREATE_TOPICS=${KRAFT_DEFAULT_TOPICS}
      - KRAFT_PARTITIONS_PER_TOPIC=${KRAFT_PARTITIONS_PER_TOPIC}
      - KAFKA_HEAP_OPTS=${KAFKA_HEAP_OPTS}
    volumes:
      - "./vol${KRAFT_1_ID}/kafka-data:/var/lib/kafka/data"
      - "./vol${KRAFT_1_ID}/kafka-logs:/tmp/server/"

  kafka-2:
    build: 
      context: ./kafka
      dockerfile: Dockerfile
    image: nghiadh/kafka-kraft:1.0.0
    hostname: ${KRAFT_2_HOST_NAME}
    container_name: ${KRAFT_2_CONTAINER_NAME}
    # restart: always
    ports:
      - "${KRAFT_2_BROKER_PORT}:${KRAFT_2_BROKER_PORT}"
      - "${KRAFT_2_CONTROLLER_PORT}:${KRAFT_2_CONTROLLER_PORT}"
    networks:
      - backend
    environment:
      - KAFKA_STORAGE_UUID=${KAFKA_STORAGE_UUID}
      - KRAFT_ID=${KRAFT_2_ID}
      - KRAFT_HOST_NAME=${KRAFT_2_HOST_NAME}
      - KRAFT_CONTAINER_NAME=${KRAFT_2_CONTAINER_NAME}
      - KRAFT_BROKER_PORT=${KRAFT_2_BROKER_PORT}
      - KRAFT_CONTROLLER_PORT=${KRAFT_2_CONTROLLER_PORT}
      - KRAFT_QUORUM_VOTERS=${KRAFT_QUORUM_VOTERS}
      - KRAFT_CREATE_TOPICS=${KRAFT_DEFAULT_TOPICS}
      - KRAFT_PARTITIONS_PER_TOPIC=${KRAFT_PARTITIONS_PER_TOPIC}
      - KAFKA_HEAP_OPTS=${KAFKA_HEAP_OPTS}
    volumes:
      - "./vol${KRAFT_2_ID}/kafka-data:/var/lib/kafka/data"
      - "./vol${KRAFT_2_ID}/kafka-logs:/tmp/server/"

networks:
  backend:
    name: backend