version: "3.8"

services:
  kafka-1:
    build: 
      context: ./kafka
      dockerfile: Dockerfile
    image: ${DOCKERHUB_ACCOUNT}/${KAFKA_IMAGE_NAME}:${KAFKA_IMAGE_VERSION}
    hostname: ${KRAFT_1_HOST_NAME}
    container_name: ${KRAFT_1_CONTAINER_NAME}
    # restart: always
    ports:
      - "${KRAFT_1_EXTERNAL_PORT}:${KRAFT_1_EXTERNAL_PORT}"
    networks:
      - backend
    environment:
      - KAFKA_STORAGE_UUID=${KAFKA_STORAGE_UUID}
      - KRAFT_ID=${KRAFT_1_ID}
      - KRAFT_HOST_NAME=${KRAFT_1_HOST_NAME}
      - KRAFT_CONTAINER_NAME=${KRAFT_1_CONTAINER_NAME}
      - KRAFT_BROKER_PORT=${KRAFT_1_BROKER_PORT}
      - KRAFT_CONTROLLER_PORT=${KRAFT_1_CONTROLLER_PORT}
      - KRAFT_EXTERNAL_PORT=${KRAFT_1_EXTERNAL_PORT}
      - KRAFT_QUORUM_VOTERS=${KRAFT_QUORUM_VOTERS}
    volumes:
      - "${KRAFT_1_DATA_VOL}:/var/lib/kafka/data"
      - "${KRAFT_1_LOGS_VOL}:/tmp/server/"

  kafka-2:
    build: 
      context: ./kafka
      dockerfile: Dockerfile
    image: ${DOCKERHUB_ACCOUNT}/${KAFKA_IMAGE_NAME}:${KAFKA_IMAGE_VERSION}
    hostname: ${KRAFT_2_HOST_NAME}
    container_name: ${KRAFT_2_CONTAINER_NAME}
    # restart: always
    ports:
      - "${KRAFT_2_EXTERNAL_PORT}:${KRAFT_2_EXTERNAL_PORT}"
    networks:
      - backend
    environment:
      - KAFKA_STORAGE_UUID=${KAFKA_STORAGE_UUID}
      - KRAFT_ID=${KRAFT_2_ID}
      - KRAFT_HOST_NAME=${KRAFT_2_HOST_NAME}
      - KRAFT_CONTAINER_NAME=${KRAFT_2_CONTAINER_NAME}
      - KRAFT_BROKER_PORT=${KRAFT_2_BROKER_PORT}
      - KRAFT_CONTROLLER_PORT=${KRAFT_2_CONTROLLER_PORT}
      - KRAFT_EXTERNAL_PORT=${KRAFT_2_EXTERNAL_PORT}
      - KRAFT_QUORUM_VOTERS=${KRAFT_QUORUM_VOTERS}
    volumes:
      - "${KRAFT_2_DATA_VOL}:/var/lib/kafka/data"
      - "${KRAFT_2_LOGS_VOL}:/tmp/server/"

networks:
  backend:
    name: backend